name: QualityContol

on:
  pull_request:
    paths:
      - 'book/**'
      - '.github/workflows/qaqc.yaml'
    branches:
      - main

env:
  DOCKER_IMAGE: uwhackweek/snowex:latest

jobs:
  quality-control:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Ensure Clean Notebooks
      continue-on-error: true
      run: |
        pip install nb-clean==2.0.2
        find book -name "*ipynb" | xargs nb-clean check --preserve-cell-metadata

    # NOTE: this isn't a comprehensive spellcheck, just common typos
    - name: Spellcheck
      continue-on-error: true
      uses: codespell-project/actions-codespell@master
      with:
        skip: .github/workflows/qaqc.yaml,./book/tutorials/geospatial/geospatial_cookbook_rendered.ipynb
        ignore_words_list: hist,MAPE,te
        check_filenames: true
        check_hidden: true
        only_warn: false

    - name: Pull Docker Image
      run: |
        docker pull $DOCKER_IMAGE
        docker images

    # borrowed from https://github.com/ProjectPythia/pythia-foundations/blob/main/.github/workflows/link-checker.yaml
    - name: Disable Notebook Execution
      shell: python
      run: |
        import yaml
        with open('./book/_config.yml') as f:
          data = yaml.safe_load(f)
          data['execute']['execute_notebooks'] = 'off'
        with open('./book/_config.yml', 'w') as f:
          yaml.dump(data, f)

    # NOTE: create separate _config.yml to pass --config (and skip executing notebooks?)
    - name: Check External Links
      run: |
        docker run -u root -v ${{ github.workspace }}:/home/jovyan:rw $DOCKER_IMAGE jb build book --builder linkcheck
